# Uncomment the next line to define a global platform for your project
# platform :ios, ’10.0’

target 'ReuseableSwift3' do
pod 'Alamofire'
pod 'ObjectMapper'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReuseableSwift3

  target 'ReuseableSwift3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReuseableSwift3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
